### ISSUE TITLE
Add examples of Java Streams

### ISSUE THREAD

**Issue by Someshbose** [Someshbose/TravisTest#4]

**Comment by rishika-singh49** [comment]
Do we have to make a java program?

**Comment by Pranshu-Tripathi** [comment]
I would Like to work on this ... please assign it to  me

**Comment by kingaj** [comment]
hi i'm able to add example of java streams can you assign to me

**Comment by Someshbose** [comment]
@rishika-singh49 @kingaj @Pranshu-Tripathi thanks for showing interest. In fact you all can work on this. I will create sub-stories soon. Give me some time. I will update here.

**Comment by Someshbose** [comment]
- [ ] create a model class of DataEntity.  DataEntity should contains 1. id, 2. name, 3. mail-id, 4. salary, 5.address.

- [ ] create a method that will check for valid mail-ids and salary should be more the amount passed as parameter. Please note you should only use Java Streams to filter out the DataEntity list.

```
public List<DataEntity> filter(float salary, List<DataEntity> list){

}
```
